# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86ac4067270a15df15e24b2dbe09d3797e43177073ca15fbca1770b139b52696dab5943b3128577fdec27204e984bb495816a0ef6c7af957825064b089003643
  google_maps_api: AIzaSyBe6RxV5rcs41ru03y4Bhgi_4_z-KANxkE
  facebook_key_base: 908454422513063
  facebook_secret_base: 0d9ac3b43a00f45fa58d111015d59611
test:
  secret_key_base: ad86dce659793ce68d0db82e58774cce49d5c9117499d1788f0bb47d9bc55f46aa715e28f92f451f270a311cd905785f6d968b562779776d409eb2e17e974f7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_api: AIzaSyBe6RxV5rcs41ru03y4Bhgi_4_z-KANxkE